// app/layout.jsx
import "./globals.css"; // Your global styles
import { ReduxProvider } from "@/providers/ReduxProvider"; // Or wherever you put your ReduxProvider

export const metadata = {
  title: "Next.js Redux App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
